version: "3.1"

services:
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0

    restart: always

    #network_mode: "host"

    environment:
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./data/esdata:/usr/share/elasticsearch/data
      #- ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.2.0

    restart: always

    #network_mode: "host"

    depends_on:
      - elasticsearch
    
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

    ports:
      - 5601:5601


  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.2.0
    
    restart: always
    
    #network_mode: "host"

    depends_on:
      - elasticsearch
    
    ports:
      - 57175:57175
      - 9600:9600

    volumes:
      - "./pipeline-sensorstream:/usr/share/logstash/pipeline/"


  grafana:
    image: grafana/grafana:6.2.4

    restart: always

    # network_mode: host

    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=admin"

    volumes:
      - "./data/grafana:/var/lib/grafana"

    ports:
      - "3000:3000"
    